language: node_js
node_js:
- 6
install: npm install
script:
- npm run build
deploy:
  - provider: npm
    email: israel.lavi@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: islavi/ng2-component-lab