language: node_js
node_js:
  - 6
install: npm install
script:
  - npm run build
before_deploy:
  - ./deploy.sh
  - cd release
deploy:
  - provider: npm
    email: israel.lavi@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
      repo: islavi/npm-test
